/*
 * user_remainTimer.h
 *
 *  Created on: 2021年12月3日
 *      Author: Sky
 */

#ifndef PROJ_USER_INC_USER_REMAINTIMER_H_
#define PROJ_USER_INC_USER_REMAINTIMER_H_
#include "protocol.h"
#include "light.h"

extern volatile uint8 vCalcTime1s;
extern volatile uint8 fIsUpdateRemainTimer;

#define	STANDER_MIN_60S						6
#define	QUICK_MIN_40S							4
#define	QUICK_MIN_50S							5
#define	SLOW_MIN_70S							7
#define	SLOW_MIN_80S							8

#define	MW_MAX_TIMER_CONST					(1.0/(PWM_MAX_CW*1.0/PWM_FRQ_CONST))						//80min
#define	CW_MAX_TIMER_CONST					(MW_MAX_TIMER_CONST*(CW_POWER_RATING/MW_POWER_RATING))


#define	REMAIN_TIME_STEP1_THRESHOLD			BATT_VOLT_MIN
#define	REMAIN_TIME_STEP1_START				0//MIN
#define	REMAIN_TIME_STEP1_LAST				3//19//8//MIN
#define	REMAIN_TIME_STEP1_VOLT_LAST			(REMAIN_TIME_STEP2_THRESHOLD-REMAIN_TIME_STEP1_THRESHOLD)

#define	REMAIN_TIME_STEP2_THRESHOLD			3.48//3.53
#define	REMAIN_TIME_STEP2_START				REMAIN_TIME_STEP1_LAST//MIN
#define	REMAIN_TIME_STEP2_LAST				5//21//23//MIN
#define	REMAIN_TIME_STEP2_VOLT_LAST			(REMAIN_TIME_STEP3_THRESHOLD-REMAIN_TIME_STEP2_THRESHOLD)

#define	REMAIN_TIME_STEP3_THRESHOLD			3.65//3.67
#define	REMAIN_TIME_STEP3_START				(REMAIN_TIME_STEP2_LAST+REMAIN_TIME_STEP2_START)//MIN
#define	REMAIN_TIME_STEP3_LAST				20//20//17//MIN
#define	REMAIN_TIME_STEP3_VOLT_LAST			(REMAIN_TIME_STEP4_THRESHOLD-REMAIN_TIME_STEP3_THRESHOLD)

#define	REMAIN_TIME_STEP4_THRESHOLD			3.75
#define	REMAIN_TIME_STEP4_START				(REMAIN_TIME_STEP3_LAST+REMAIN_TIME_STEP3_START)//MIN
#define	REMAIN_TIME_STEP4_LAST				45//27//MIN
#define	REMAIN_TIME_STEP4_VOLT_LAST			(REMAIN_TIME_STEP5_THRESHOLD-REMAIN_TIME_STEP4_THRESHOLD)

#define	REMAIN_TIME_STEP5_START				(REMAIN_TIME_STEP4_LAST+REMAIN_TIME_STEP4_START)//MIN
#define	REMAIN_TIME_STEP5_THRESHOLD			4.00
#define	REMAIN_TIME_STEP5_LAST				12//8//MIN

#define	REMAIN_TIME_STEP5_VOLT_LAST			(REMAIN_TIME_STEP6_THRESHOLD-REMAIN_TIME_STEP5_THRESHOLD)

#define	REMAIN_TIME_STEP6_THRESHOLD			4.16

uint16 calcRemainTime(uint8 ignoreCompare);
void freshRemainTimeCheck(void);

#endif /* PROJ_USER_INC_USER_REMAINTIMER_H_ */
